apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow-tool.fullname" . }}-scheduler
spec:
  template:
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.airflow.images.airflow.repository }}:{{ .Values.airflow.images.airflow.tag }}"
          resources:
            {{- toYaml .Values.airflow.scheduler.resources | nindent 12 }}
          livenessProbe:
            timeoutSeconds: {{ .Values.airflow.scheduler.livenessProbeTimeoutSeconds }}
